repos:
  - repo: local
    hooks:
      - id: aac-generate
        name: AAC Generate
        entry: bash -lc "npm run aac:gen && npm run aac:validate"
        language: system
        files: ^(iac/|services/|apps/|apis/|docs/adr/)
