system:
  name: bond-math
  description: Bond mathematics calculation service
  repository: https://github.com/chrislyons-dev/bond-math.git

project:
  name: bond-math
  description: Bond mathematics calculation service

paths:
  output: ./output
  logs: ./output/logs
  ir_out: ./output/bond-math-ir.json
  dsl_out: ./output/bond-math.dsl
  render_out: ./output/diagrams
  docs_out: ./output/docs

allowedPluginPaths:
  - ./plugins
  - ./custom-plugins
allowedAbsolutePaths:
  - /users/chris/git/bond-math
  - C:\users\chris\git\bond-math

extractors:
  # Wrangler deployment extractor for Cloudflare Workers
  - use: extractors/builtin/basic-wrangler
    inputs:
      include:
        - '/users/chris/git/bond-math/ui/wrangler.toml'
        - '/users/chris/git/bond-math/iac/workers/daycount.toml'
        - '/users/chris/git/bond-math/iac/workers/gateway.toml'
        - '/users/chris/git/bond-math/iac/workers/metrics.toml'
        - '/users/chris/git/bond-math/iac/workers/pricing.toml'
        - '/users/chris/git/bond-math/iac/workers/valuation.toml'

  - use: extractors/builtin/basic-astro
    inputs:
      include:
        - '/users/chris/git/bond-math/ui/**/*.astro'
      exclude:
        - '**/*.test.astro'
        - '**/.astro/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/node_modules/**'
        - '**/*.test.*'
        - '**/*.spec.*'
        - '**/test/**'
        - '**/tests/**'
        - '**/vitest.config.ts'

  - use: extractors/builtin/basic-node
    inputs:
      include:
        - '/users/chris/git/bond-math/ui/**/*.js'
        - '/users/chris/git/bond-math/ui/**/*.cjs'
        - '/users/chris/git/bond-math/ui/**/*.mjs'
        - '/users/chris/git/bond-math/ui/**/*.jsx'
        - '/users/chris/git/bond-math/ui/**/*.ts'
        - '/users/chris/git/bond-math/ui/**/*.tsx'
      exclude:
        - '**/node_modules/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/*.test.*'
        - '**/*.spec.*'
        - '**/test/**'
        - '**/tests/**'
        - '**/vitest.config.ts'

  - use: extractors/builtin/basic-node
    inputs:
      include:
        - '/users/chris/git/bond-math/services/gateway/**/*.js'
        - '/users/chris/git/bond-math/services/gateway/**/*.jsx'
        - '/users/chris/git/bond-math/services/gateway/**/*.ts'
        - '/users/chris/git/bond-math/services/gateway/**/*.tsx'
      exclude:
        - '**/node_modules/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/*.test.*'
        - '**/*.spec.*'
        - '**/test/**'
        - '**/tests/**'
        - '**/vitest.config.ts'

  - use: extractors/builtin/basic-node
    inputs:
      include:
        - '/users/chris/git/bond-math/services/daycount/**/*.js'
        - '/users/chris/git/bond-math/services/daycount/**/*.jsx'
        - '/users/chris/git/bond-math/services/daycount/**/*.ts'
        - '/users/chris/git/bond-math/services/daycount/**/*.tsx'
      exclude:
        - '**/node_modules/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/*.test.*'
        - '**/*.spec.*'
        - '**/test/**'
        - '**/tests/**'
        - '**/vitest.config.ts'

  - use: extractors/builtin/basic-python
    inputs:
      include:
        - '/users/chris/git/bond-math/services/bond-valuation/**/*.py'
        - '/users/chris/git/bond-math/services/metrics/**/*.py'
        - '/users/chris/git/bond-math/services/pricing/**/*.py'
      exclude:
        - '**/__pycache__/**'
        - '**/venv/**'
        - '**/*.venv/***'
        - '**/test/**'
        - '**/tests/**'
        - '**/flarelette/**'
        - '**/dateutil/**'
        - '**/pythonjsonlogger/**'
        - '**/six.py'

# ir json in, ir json out (or errors)
validators:
  - use: validators/builtin/base-validator

# ir json in, dsl out
generators:
  - use: generators/builtin/structurizr

# dsl in, images out
# Renderers run sequentially - order matters!
# 1. Export DSL to PlantUML/Mermaid
# 2. Render PlantUML to PNG images
renderers:
  - use: renderers/builtin/structurizr-export
  - use: renderers/builtin/plantuml-render

# dsl & images in, (likely markdown) docs out
docs:
  - use: docs/builtin/markdown-docs
