@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.corepath__resolvepluginpath>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.corepath__resolvesecurepath>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.corepath__resolveusercontentpath>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.corepath__validatepathsecurity>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==core/path__validatepathsecurity\n<size:10>[Component: function]</size>\n\nValidate path for security issues" <<Application.Application.corepath__validatepathsecurity>> as Application.Application.corepath__validatepathsecurity
  rectangle "==core/path__resolvesecurepath\n<size:10>[Component: function]</size>\n\nSecurely resolve a user-provided path with validation" <<Application.Application.corepath__resolvesecurepath>> as Application.Application.corepath__resolvesecurepath
  rectangle "==core/path__resolveusercontentpath\n<size:10>[Component: function]</size>\n\nConvenience function for resolving user content paths (themes, input files)\nUses 'config-relative' strategy by default" <<Application.Application.corepath__resolveusercontentpath>> as Application.Application.corepath__resolveusercontentpath
  rectangle "==core/path__resolvepluginpath\n<size:10>[Component: function]</size>\n\nConvenience function for resolving plugin paths\nUses 'cli-relative' strategy by default" <<Application.Application.corepath__resolvepluginpath>> as Application.Application.corepath__resolvepluginpath
}

@enduml