@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.cli__loadyamlifexists>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.cli__parseargs>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.cli__run>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.cli__stagelistfromarg>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.cli__usageandexit>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==cli__usageandexit\n<size:10>[Component: function]</size>" <<Application.Application.cli__usageandexit>> as Application.Application.cli__usageandexit
  rectangle "==cli__parseargs\n<size:10>[Component: function]</size>" <<Application.Application.cli__parseargs>> as Application.Application.cli__parseargs
  rectangle "==cli__stagelistfromarg\n<size:10>[Component: function]</size>" <<Application.Application.cli__stagelistfromarg>> as Application.Application.cli__stagelistfromarg
  rectangle "==cli__loadyamlifexists\n<size:10>[Component: function]</size>" <<Application.Application.cli__loadyamlifexists>> as Application.Application.cli__loadyamlifexists
  rectangle "==cli__run\n<size:10>[Component: function]</size>" <<Application.Application.cli__run>> as Application.Application.cli__run
}

@enduml