@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.validators__basevalidator>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.validators__run>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==validators__run\n<size:10>[Component: function]</size>\n\nExecute the validation stage" <<Application.Application.validators__run>> as Application.Application.validators__run
  rectangle "==validators__basevalidator\n<size:10>[Component: function]</size>\n\nValidates the IR against the Zod schema. Throws if invalid." <<Application.Application.validators__basevalidator>> as Application.Application.validators__basevalidator
}

@enduml