graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      131("<div style='font-weight: bold'>basic_python__parsefiles</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Parse Python files using<br />Python AST parser script</div>")
      style 131 fill:#85bbf0,stroke:#5d82a8,color:#000000
      132("<div style='font-weight: bold'>basic_python__runpythonparser</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Run Python parser script and<br />return JSON output</div>")
      style 132 fill:#85bbf0,stroke:#5d82a8,color:#000000
      133("<div style='font-weight: bold'>basic_python__maptofileextraction</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python parser output to<br />FileExtraction format</div>")
      style 133 fill:#85bbf0,stroke:#5d82a8,color:#000000
      134("<div style='font-weight: bold'>basic_python__mapclass</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python class to<br />ExtractedClass</div>")
      style 134 fill:#85bbf0,stroke:#5d82a8,color:#000000
      135("<div style='font-weight: bold'>basic_python__mapmethod</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python method to<br />ExtractedMethod</div>")
      style 135 fill:#85bbf0,stroke:#5d82a8,color:#000000
      136("<div style='font-weight: bold'>basic_python__mapproperty</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python property to<br />ExtractedProperty</div>")
      style 136 fill:#85bbf0,stroke:#5d82a8,color:#000000
      137("<div style='font-weight: bold'>basic_python__mapfunction</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python function to<br />ExtractedFunction</div>")
      style 137 fill:#85bbf0,stroke:#5d82a8,color:#000000
      138("<div style='font-weight: bold'>basic_python__maptype</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python type definition to<br />ExtractedType</div>")
      style 138 fill:#85bbf0,stroke:#5d82a8,color:#000000
      139("<div style='font-weight: bold'>basic_python__mapparameter</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python parameter to<br />ParameterInfo</div>")
      style 139 fill:#85bbf0,stroke:#5d82a8,color:#000000
      140("<div style='font-weight: bold'>basic_python__parsedocstring</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Parse Python docstring into<br />DocInfo Enhanced in Phase 2<br />to use parsed<br />Google/NumPy/Sphinx<br />docstrings</div>")
      style 140 fill:#85bbf0,stroke:#5d82a8,color:#000000
      141("<div style='font-weight: bold'>basic_python__extractdeprecation</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Extract deprecation info from<br />docstring</div>")
      style 141 fill:#85bbf0,stroke:#5d82a8,color:#000000
      142("<div style='font-weight: bold'>basic_python__extractreturndescription</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Extract return description<br />from docstring</div>")
      style 142 fill:#85bbf0,stroke:#5d82a8,color:#000000
      143("<div style='font-weight: bold'>basic_python__getvisibility</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Determine visibility from<br />Python name convention -<br />__name: private - _name:<br />protected - name: public</div>")
      style 143 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end