graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      30("<div style='font-weight: bold'>validators__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the validation stage</div>")
      style 30 fill:#85bbf0,stroke:#5d82a8,color:#000000
      84("<div style='font-weight: bold'>validators__basevalidator</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Validates the IR against the<br />Zod schema. Throws if<br />invalid.</div>")
      style 84 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end