graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      47("<div style='font-weight: bold'>core/path__validatepathsecurity</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Validate path for security<br />issues</div>")
      style 47 fill:#85bbf0,stroke:#5d82a8,color:#000000
      48("<div style='font-weight: bold'>core/path__resolvesecurepath</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Securely resolve a<br />user-provided path with<br />validation</div>")
      style 48 fill:#85bbf0,stroke:#5d82a8,color:#000000
      49("<div style='font-weight: bold'>core/path__resolveusercontentpath</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Convenience function for<br />resolving user content paths<br />(themes, input files) Uses<br />'config-relative' strategy by<br />default</div>")
      style 49 fill:#85bbf0,stroke:#5d82a8,color:#000000
      50("<div style='font-weight: bold'>core/path__resolvepluginpath</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Convenience function for<br />resolving plugin paths Uses<br />'cli-relative' strategy by<br />default</div>")
      style 50 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end