graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      34("<div style='font-weight: bold'>docs__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the documentation<br />stage</div>")
      style 34 fill:#85bbf0,stroke:#5d82a8,color:#000000
      69("<div style='font-weight: bold'>docs__markdowndocs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Generate markdown<br />documentation</div>")
      style 69 fill:#85bbf0,stroke:#5d82a8,color:#000000
      70("<div style='font-weight: bold'>docs__finddiagramsforview</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find diagram files for a<br />specific view type</div>")
      style 70 fill:#85bbf0,stroke:#5d82a8,color:#000000
      71("<div style='font-weight: bold'>docs__finddiagramsforcontainer</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find component diagrams for a<br />specific container</div>")
      style 71 fill:#85bbf0,stroke:#5d82a8,color:#000000
      72("<div style='font-weight: bold'>docs__findclassdiagramsforcomponent</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find class diagrams for a<br />specific component</div>")
      style 72 fill:#85bbf0,stroke:#5d82a8,color:#000000
      73("<div style='font-weight: bold'>docs__sanitizefilename</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 73 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end