graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      33("<div style='font-weight: bold'>docs.run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the documentation<br />stage</div>")
      style 33 fill:#85bbf0,stroke:#5d82a8,color:#000000
      76("<div style='font-weight: bold'>docs.markdownDocs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Generate markdown<br />documentation</div>")
      style 76 fill:#85bbf0,stroke:#5d82a8,color:#000000
      77("<div style='font-weight: bold'>docs.findDiagramsForView</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find diagram files for a<br />specific view type</div>")
      style 77 fill:#85bbf0,stroke:#5d82a8,color:#000000
      78("<div style='font-weight: bold'>docs.findDiagramsForContainer</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find component diagrams for a<br />specific container</div>")
      style 78 fill:#85bbf0,stroke:#5d82a8,color:#000000
      79("<div style='font-weight: bold'>docs.findClassDiagramsForComponent</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find class diagrams for a<br />specific component</div>")
      style 79 fill:#85bbf0,stroke:#5d82a8,color:#000000
      80("<div style='font-weight: bold'>docs.sanitizeFileName</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 80 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end