graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      139["<div style='font-weight: bold'>basic__maptoir</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map file extractions to<br />ArchletteIR</div>"]
      style 139 fill:#dddddd,stroke:#9a9a9a,color:#000000
      140["<div style='font-weight: bold'>basic__mapcomponenttoir</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map ComponentInfo to<br />Component</div>"]
      style 140 fill:#dddddd,stroke:#9a9a9a,color:#000000
      141["<div style='font-weight: bold'>basic__mapactortoir</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map ActorInfo to Actor</div>"]
      style 141 fill:#dddddd,stroke:#9a9a9a,color:#000000
      142["<div style='font-weight: bold'>basic__maprelationshipstoir</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map relationships to<br />Relationship[] Creates<br />bidirectional actor<br />relationships</div>"]
      style 142 fill:#dddddd,stroke:#9a9a9a,color:#000000
      143["<div style='font-weight: bold'>basic__deduplicaterelationships</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate relationships by<br />source+destination</div>"]
      style 143 fill:#dddddd,stroke:#9a9a9a,color:#000000
      144["<div style='font-weight: bold'>basic__mapclasstocodeitem</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map ExtractedClass to<br />CodeItem</div>"]
      style 144 fill:#dddddd,stroke:#9a9a9a,color:#000000
      145["<div style='font-weight: bold'>basic__mapmethodtocodeitem</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map ExtractedMethod to<br />CodeItem</div>"]
      style 145 fill:#dddddd,stroke:#9a9a9a,color:#000000
      146["<div style='font-weight: bold'>basic__mapfunctiontocodeitem</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map ExtractedFunction to<br />CodeItem</div>"]
      style 146 fill:#dddddd,stroke:#9a9a9a,color:#000000
      147["<div style='font-weight: bold'>basic__maptypetocodeitem</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map ExtractedType to CodeItem</div>"]
      style 147 fill:#dddddd,stroke:#9a9a9a,color:#000000
      70["<div style='font-weight: bold'>basic__createemptyir</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Create empty IR when no files<br />found</div>"]
      style 70 fill:#dddddd,stroke:#9a9a9a,color:#000000
      71["<div style='font-weight: bold'>basic__basicpython</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Basic Python extractor<br />Analyzes Python source code<br />and extracts architectural<br />components</div>"]
      style 71 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end