graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      20["<div style='font-weight: bold'>cli__usageandexit</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 20 fill:#dddddd,stroke:#9a9a9a,color:#000000
      21["<div style='font-weight: bold'>cli__parseargs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 21 fill:#dddddd,stroke:#9a9a9a,color:#000000
      22["<div style='font-weight: bold'>cli__stagelistfromarg</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 22 fill:#dddddd,stroke:#9a9a9a,color:#000000
      23["<div style='font-weight: bold'>cli__loadyamlifexists</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 23 fill:#dddddd,stroke:#9a9a9a,color:#000000
      24["<div style='font-weight: bold'>cli__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 24 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end