graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      28["<div style='font-weight: bold'>renderers__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the rendering stage</div>"]
      style 28 fill:#dddddd,stroke:#9a9a9a,color:#000000
      84["<div style='font-weight: bold'>renderers__plantumlrender</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Render PlantUML files to PNG<br />images</div>"]
      style 84 fill:#dddddd,stroke:#9a9a9a,color:#000000
      85["<div style='font-weight: bold'>renderers__structurizrexport</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Export Structurizr DSL to<br />PlantUML and Mermaid formats</div>"]
      style 85 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end