graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - @chrislyons-dev/archlette - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 4 ["@chrislyons-dev/archlette"]
      style 4 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      25["<div style='font-weight: bold'>4-render/index.ts::run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the rendering stage</div>"]
      style 25 fill:#dddddd,stroke:#9a9a9a,color:#000000
      79["<div style='font-weight: bold'>plantuml-render.ts::plantumlrender</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Render PlantUML files to PNG<br />images</div>"]
      style 79 fill:#dddddd,stroke:#9a9a9a,color:#000000
      80["<div style='font-weight: bold'>structurizr-export.ts::structurizrexport</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Export Structurizr DSL to<br />PlantUML and Mermaid formats</div>"]
      style 80 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end