graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - System Context"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>End user who runs archlette<br />commands</div>"]
    style 1 fill:#dddddd,stroke:#9a9a9a,color:#000000
    2["<div style='font-weight: bold'>FileSystem</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>File system for reading and<br />writing files</div>"]
    style 2 fill:#dddddd,stroke:#9a9a9a,color:#000000
    3["<div style='font-weight: bold'>@chrislyons-dev/archlette</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Architecture-as-Code toolkit<br />for automated diagrams, docs,<br />and releases.</div>"]
    style 3 fill:#dddddd,stroke:#9a9a9a,color:#000000

    3-. "<div>Uses FileSystem for external<br />system integration</div><div style='font-size: 70%'></div>" .->2
    1-. "<div>Interacts with CLI</div><div style='font-size: 70%'></div>" .->3
    2-. "<div>Interacts with core</div><div style='font-size: 70%'></div>" .->3
    3-. "<div>Interacts with User</div><div style='font-size: 70%'></div>" .->1
  end