graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      25["<div style='font-weight: bold'>extractors__aggregateirs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Aggregate multiple<br />ArchletteIR objects into a<br />single unified IR</div>"]
      style 25 fill:#dddddd,stroke:#9a9a9a,color:#000000
      26["<div style='font-weight: bold'>extractors__deduplicatebyid</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate array of entities<br />by their ID field</div>"]
      style 26 fill:#dddddd,stroke:#9a9a9a,color:#000000
      27["<div style='font-weight: bold'>extractors__deduplicatebyname</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate array of entities<br />by their name field</div>"]
      style 27 fill:#dddddd,stroke:#9a9a9a,color:#000000
      28["<div style='font-weight: bold'>extractors__deduplicaterelationships</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate relationships by<br />source+destination+stereotype<br />combination</div>"]
      style 28 fill:#dddddd,stroke:#9a9a9a,color:#000000
      29["<div style='font-weight: bold'>extractors__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the extraction stage</div>"]
      style 29 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end