graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      33("<div style='font-weight: bold'>default_container__renderers__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the rendering stage</div>")
      style 33 fill:#85bbf0,stroke:#5d82a8,color:#000000
      96("<div style='font-weight: bold'>default_container__renderers__plantumlrender</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Render PlantUML files to PNG<br />images</div>")
      style 96 fill:#85bbf0,stroke:#5d82a8,color:#000000
      97("<div style='font-weight: bold'>default_container__renderers__structurizrexport</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Export Structurizr DSL to<br />PlantUML and Mermaid formats</div>")
      style 97 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end