graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - @chrislyons-dev/archlette - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["@chrislyons-dev/archlette"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      27["<div style='font-weight: bold'>2-validate/index.ts::run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the validation stage</div>"]
      style 27 fill:#dddddd,stroke:#9a9a9a,color:#000000
      85["<div style='font-weight: bold'>base-validator.ts::basevalidator</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Validates the IR against the<br />Zod schema. Throws if<br />invalid.</div>"]
      style 85 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end