graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      33["<div style='font-weight: bold'>docs__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the documentation<br />stage</div>"]
      style 33 fill:#dddddd,stroke:#9a9a9a,color:#000000
      64["<div style='font-weight: bold'>docs__markdowndocs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Generate markdown<br />documentation</div>"]
      style 64 fill:#dddddd,stroke:#9a9a9a,color:#000000
      65["<div style='font-weight: bold'>docs__finddiagramsforview</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find diagram files for a<br />specific view type</div>"]
      style 65 fill:#dddddd,stroke:#9a9a9a,color:#000000
      66["<div style='font-weight: bold'>docs__finddiagramsforcomponent</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find component diagrams for a<br />specific component</div>"]
      style 66 fill:#dddddd,stroke:#9a9a9a,color:#000000
      67["<div style='font-weight: bold'>docs__findclassdiagramsforcomponent</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find class diagrams for a<br />specific component</div>"]
      style 67 fill:#dddddd,stroke:#9a9a9a,color:#000000
      68["<div style='font-weight: bold'>docs__sanitizefilename</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 68 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end