graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - @chrislyons-dev/archlette - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 4 ["@chrislyons-dev/archlette"]
      style 4 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      26["<div style='font-weight: bold'>5-docs/index.ts::run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 26 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end