graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      146("<div style='font-weight: bold'>default_container__basic_python__parsefiles</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Parse Python files using<br />Python AST parser script</div>")
      style 146 fill:#85bbf0,stroke:#5d82a8,color:#000000
      147("<div style='font-weight: bold'>default_container__basic_python__runpythonparser</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Run Python parser script and<br />return JSON output</div>")
      style 147 fill:#85bbf0,stroke:#5d82a8,color:#000000
      148("<div style='font-weight: bold'>default_container__basic_python__maptofileextraction</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python parser output to<br />FileExtraction format</div>")
      style 148 fill:#85bbf0,stroke:#5d82a8,color:#000000
      149("<div style='font-weight: bold'>default_container__basic_python__mapclass</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python class to<br />ExtractedClass</div>")
      style 149 fill:#85bbf0,stroke:#5d82a8,color:#000000
      150("<div style='font-weight: bold'>default_container__basic_python__mapmethod</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python method to<br />ExtractedMethod</div>")
      style 150 fill:#85bbf0,stroke:#5d82a8,color:#000000
      151("<div style='font-weight: bold'>default_container__basic_python__mapproperty</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python property to<br />ExtractedProperty</div>")
      style 151 fill:#85bbf0,stroke:#5d82a8,color:#000000
      152("<div style='font-weight: bold'>default_container__basic_python__mapfunction</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python function to<br />ExtractedFunction</div>")
      style 152 fill:#85bbf0,stroke:#5d82a8,color:#000000
      153("<div style='font-weight: bold'>default_container__basic_python__maptype</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python type definition to<br />ExtractedType</div>")
      style 153 fill:#85bbf0,stroke:#5d82a8,color:#000000
      154("<div style='font-weight: bold'>default_container__basic_python__mapparameter</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Map Python parameter to<br />ParameterInfo</div>")
      style 154 fill:#85bbf0,stroke:#5d82a8,color:#000000
      155("<div style='font-weight: bold'>default_container__basic_python__parsedocstring</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Parse Python docstring into<br />DocInfo Enhanced in Phase 2<br />to use parsed<br />Google/NumPy/Sphinx<br />docstrings</div>")
      style 155 fill:#85bbf0,stroke:#5d82a8,color:#000000
      156("<div style='font-weight: bold'>default_container__basic_python__extractdeprecation</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Extract deprecation info from<br />docstring</div>")
      style 156 fill:#85bbf0,stroke:#5d82a8,color:#000000
      157("<div style='font-weight: bold'>default_container__basic_python__extractreturndescription</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Extract return description<br />from docstring</div>")
      style 157 fill:#85bbf0,stroke:#5d82a8,color:#000000
      158("<div style='font-weight: bold'>default_container__basic_python__getvisibility</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Determine visibility from<br />Python name convention -<br />__name: private - _name:<br />protected - name: public</div>")
      style 158 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end