graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      20("<div style='font-weight: bold'>default_container__cli__usageandexit</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 20 fill:#85bbf0,stroke:#5d82a8,color:#000000
      21("<div style='font-weight: bold'>default_container__cli__parseargs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 21 fill:#85bbf0,stroke:#5d82a8,color:#000000
      22("<div style='font-weight: bold'>default_container__cli__stagelistfromarg</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 22 fill:#85bbf0,stroke:#5d82a8,color:#000000
      23("<div style='font-weight: bold'>default_container__cli__run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 23 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end