graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - @chrislyons-dev/archlette - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["@chrislyons-dev/archlette"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      16["<div style='font-weight: bold'>cli.ts::usageandexit</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 16 fill:#dddddd,stroke:#9a9a9a,color:#000000
      17["<div style='font-weight: bold'>cli.ts::parseargs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 17 fill:#dddddd,stroke:#9a9a9a,color:#000000
      18["<div style='font-weight: bold'>cli.ts::stagelistfromarg</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 18 fill:#dddddd,stroke:#9a9a9a,color:#000000
      19["<div style='font-weight: bold'>cli.ts::loadyamlifexists</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 19 fill:#dddddd,stroke:#9a9a9a,color:#000000
      20["<div style='font-weight: bold'>cli.ts::run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 20 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end