graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - @chrislyons-dev/archlette - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["@chrislyons-dev/archlette"]
      style 8 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      29["<div style='font-weight: bold'>4-render/index.ts::run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the rendering stage</div>"]
      style 29 fill:#dddddd,stroke:#9a9a9a,color:#000000
      83["<div style='font-weight: bold'>plantuml-render.ts::plantumlrender</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Render PlantUML files to PNG<br />images</div>"]
      style 83 fill:#dddddd,stroke:#9a9a9a,color:#000000
      84["<div style='font-weight: bold'>structurizr-export.ts::structurizrexport</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Export Structurizr DSL to<br />PlantUML and Mermaid formats</div>"]
      style 84 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end