graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - System Context"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>End user who runs archlette<br />commands</div>"]
    style 1 fill:#08427b,stroke:#052e56,color:#ffffff
    2("<div style='font-weight: bold'>FileSystem</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>File system for reading and<br />writing files</div>")
    style 2 fill:#999999,stroke:#6b6b6b,color:#ffffff
    3("<div style='font-weight: bold'>Github Structurizr Repo</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>The github repo hosting the<br />Structurizr CLI releases.<br />https://github.com/structurizr/cli/releases/download/v${TOOL_VERSIONS.structurizr}/structurizr-cli.zip</div>")
    style 3 fill:#999999,stroke:#6b6b6b,color:#ffffff
    4("<div style='font-weight: bold'>Github PlantUML Repo</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>The github repo hosting the<br />PlantUML CLI releases.<br />https://github.com/plantuml/plantuml/releases/download/v${TOOL_VERSIONS.plantuml}/plantuml-${TOOL_VERSIONS.plantuml}.jar</div>")
    style 4 fill:#999999,stroke:#6b6b6b,color:#ffffff
    5("<div style='font-weight: bold'>Local System's unzip utility</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>The zip extraction utility on<br />the local system (unzip on<br />Unix, Expand-Archive on<br />Windows).</div>")
    style 5 fill:#999999,stroke:#6b6b6b,color:#ffffff
    6("<div style='font-weight: bold'>File System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>The local file system for<br />caching downloaded tools.</div>")
    style 6 fill:#999999,stroke:#6b6b6b,color:#ffffff
    7("<div style='font-weight: bold'>Application</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Main application container</div>")
    style 7 fill:#1168bd,stroke:#0b4884,color:#ffffff

    1-- "<div>Interacts with CLI</div><div style='font-size: 70%'></div>" -->7
    7-- "<div>Uses FileSystem for external<br />system integration</div><div style='font-size: 70%'></div>" -->2
    7-- "<div>Uses Github Structurizr Repo<br />for external system<br />integration</div><div style='font-size: 70%'></div>" -->3
    7-- "<div>Uses Github PlantUML Repo for<br />external system integration</div><div style='font-size: 70%'></div>" -->4
    7-- "<div>Uses Local System's unzip<br />utility for external system<br />integration</div><div style='font-size: 70%'></div>" -->5
    7-- "<div>Uses File System for external<br />system integration</div><div style='font-size: 70%'></div>" -->6
  end