graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["@chrislyons-dev/archlette - @chrislyons-dev/archlette - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 4 ["@chrislyons-dev/archlette"]
      style 4 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      12["<div style='font-weight: bold'>cli.ts::usageandexit</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 12 fill:#dddddd,stroke:#9a9a9a,color:#000000
      13["<div style='font-weight: bold'>cli.ts::parseargs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 13 fill:#dddddd,stroke:#9a9a9a,color:#000000
      14["<div style='font-weight: bold'>cli.ts::stagelistfromarg</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 14 fill:#dddddd,stroke:#9a9a9a,color:#000000
      15["<div style='font-weight: bold'>cli.ts::loadyamlifexists</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 15 fill:#dddddd,stroke:#9a9a9a,color:#000000
      16["<div style='font-weight: bold'>cli.ts::run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>"]
      style 16 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

  end