graph LR
  linkStyle default fill:#ffffff

  subgraph diagram [" "]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 [" "]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      33("<div style='font-weight: bold'>docs.run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the documentation<br />stage</div>")
      style 33 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      79("<div style='font-weight: bold'>docs.markdownDocs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Generate markdown<br />documentation</div>")
      style 79 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      80("<div style='font-weight: bold'>docs.findDiagramsForView</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find diagram files for a<br />specific view type</div>")
      style 80 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      81("<div style='font-weight: bold'>docs.findDiagramsForContainer</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find component diagrams for a<br />specific container</div>")
      style 81 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      82("<div style='font-weight: bold'>docs.findClassDiagramsForComponent</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Find class diagrams for a<br />specific component</div>")
      style 82 fill:#d4e8fc,stroke:#94a2b0,color:#000000
      83("<div style='font-weight: bold'>docs.sanitizeFileName</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 83 fill:#d4e8fc,stroke:#94a2b0,color:#000000
    end

  end