graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Application - Application - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 8 ["Application"]
      style 8 fill:#ffffff,stroke:#2e6295,color:#2e6295

      24("<div style='font-weight: bold'>extractors.aggregateIRs</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Aggregate multiple<br />ArchletteIR objects into a<br />single unified IR</div>")
      style 24 fill:#85bbf0,stroke:#5d82a8,color:#000000
      25("<div style='font-weight: bold'>extractors.deduplicateById</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate array of entities<br />by their ID field</div>")
      style 25 fill:#85bbf0,stroke:#5d82a8,color:#000000
      26("<div style='font-weight: bold'>extractors.deduplicateByName</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate array of entities<br />by their name field</div>")
      style 26 fill:#85bbf0,stroke:#5d82a8,color:#000000
      27("<div style='font-weight: bold'>extractors.deduplicateRelationships</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Deduplicate relationships by<br />source+destination+stereotype<br />combination</div>")
      style 27 fill:#85bbf0,stroke:#5d82a8,color:#000000
      28("<div style='font-weight: bold'>extractors.run</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Execute the extraction stage</div>")
      style 28 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end