@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.extractorsaggregateIRs>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.extractorsdeduplicateById>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.extractorsdeduplicateByName>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.extractorsdeduplicateRelationships>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.extractorsrun>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==extractors.aggregateIRs\n<size:10>[Component: function]</size>\n\nAggregate multiple ArchletteIR objects into a single unified IR" <<Application.Application.extractorsaggregateIRs>> as Application.Application.extractorsaggregateIRs
  rectangle "==extractors.deduplicateById\n<size:10>[Component: function]</size>\n\nDeduplicate array of entities by their ID field" <<Application.Application.extractorsdeduplicateById>> as Application.Application.extractorsdeduplicateById
  rectangle "==extractors.deduplicateByName\n<size:10>[Component: function]</size>\n\nDeduplicate array of entities by their name field" <<Application.Application.extractorsdeduplicateByName>> as Application.Application.extractorsdeduplicateByName
  rectangle "==extractors.deduplicateRelationships\n<size:10>[Component: function]</size>\n\nDeduplicate relationships by source+destination+stereotype combination" <<Application.Application.extractorsdeduplicateRelationships>> as Application.Application.extractorsdeduplicateRelationships
  rectangle "==extractors.run\n<size:10>[Component: function]</size>\n\nExecute the extraction stage" <<Application.Application.extractorsrun>> as Application.Application.extractorsrun
}

@enduml