@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.CLIparseArgs>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.CLIrun>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.CLIstageListFromArg>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.CLIusageAndExit>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==CLI.usageAndExit\n<size:10>[Component: function]</size>" <<Application.Application.CLIusageAndExit>> as Application.Application.CLIusageAndExit
  rectangle "==CLI.parseArgs\n<size:10>[Component: function]</size>" <<Application.Application.CLIparseArgs>> as Application.Application.CLIparseArgs
  rectangle "==CLI.stageListFromArg\n<size:10>[Component: function]</size>" <<Application.Application.CLIstageListFromArg>> as Application.Application.CLIstageListFromArg
  rectangle "==CLI.run\n<size:10>[Component: function]</size>" <<Application.Application.CLIrun>> as Application.Application.CLIrun
}

@enduml