@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.docsfindClassDiagramsForComponent>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.docsfindDiagramsForContainer>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.docsfindDiagramsForView>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.docsmarkdownDocs>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.docsrun>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.docssanitizeFileName>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==docs.run\n<size:10>[Component: function]</size>\n\nExecute the documentation stage" <<Application.Application.docsrun>> as Application.Application.docsrun
  rectangle "==docs.markdownDocs\n<size:10>[Component: function]</size>\n\nGenerate markdown documentation" <<Application.Application.docsmarkdownDocs>> as Application.Application.docsmarkdownDocs
  rectangle "==docs.findDiagramsForView\n<size:10>[Component: function]</size>\n\nFind diagram files for a specific view type" <<Application.Application.docsfindDiagramsForView>> as Application.Application.docsfindDiagramsForView
  rectangle "==docs.findDiagramsForContainer\n<size:10>[Component: function]</size>\n\nFind component diagrams for a specific container" <<Application.Application.docsfindDiagramsForContainer>> as Application.Application.docsfindDiagramsForContainer
  rectangle "==docs.findClassDiagramsForComponent\n<size:10>[Component: function]</size>\n\nFind class diagrams for a specific component" <<Application.Application.docsfindClassDiagramsForComponent>> as Application.Application.docsfindClassDiagramsForComponent
  rectangle "==docs.sanitizeFileName\n<size:10>[Component: function]</size>" <<Application.Application.docssanitizeFileName>> as Application.Application.docssanitizeFileName
}

@enduml