@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<Application.Application.pythonextractor__basicpython>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Application.Application.pythonextractor__createemptyir>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==pythonextractor__createemptyir\n<size:10>[Component: function]</size>\n\nCreate empty IR when no files found" <<Application.Application.pythonextractor__createemptyir>> as Application.Application.pythonextractor__createemptyir
  rectangle "==pythonextractor__basicpython\n<size:10>[Component: function]</size>\n\nBasic Python extractor\nAnalyzes Python source code and extracts architectural components" <<Application.Application.pythonextractor__basicpython>> as Application.Application.pythonextractor__basicpython
}

@enduml