@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application.Application.default_container__docs__findclassdiagramsforcomponent>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.default_container__docs__finddiagramsforcontainer>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.default_container__docs__finddiagramsforview>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.default_container__docs__markdowndocs>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.default_container__docs__run>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application.default_container__docs__sanitizefilename>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==default_container__docs__run\n<size:10>[Component: function]</size>\n\nExecute the documentation stage" <<Application.Application.default_container__docs__run>> as Application.Application.default_container__docs__run
  rectangle "==default_container__docs__markdowndocs\n<size:10>[Component: function]</size>\n\nGenerate markdown documentation" <<Application.Application.default_container__docs__markdowndocs>> as Application.Application.default_container__docs__markdowndocs
  rectangle "==default_container__docs__finddiagramsforview\n<size:10>[Component: function]</size>\n\nFind diagram files for a specific view type" <<Application.Application.default_container__docs__finddiagramsforview>> as Application.Application.default_container__docs__finddiagramsforview
  rectangle "==default_container__docs__finddiagramsforcontainer\n<size:10>[Component: function]</size>\n\nFind component diagrams for a specific container" <<Application.Application.default_container__docs__finddiagramsforcontainer>> as Application.Application.default_container__docs__finddiagramsforcontainer
  rectangle "==default_container__docs__findclassdiagramsforcomponent\n<size:10>[Component: function]</size>\n\nFind class diagrams for a specific component" <<Application.Application.default_container__docs__findclassdiagramsforcomponent>> as Application.Application.default_container__docs__findclassdiagramsforcomponent
  rectangle "==default_container__docs__sanitizefilename\n<size:10>[Component: function]</size>" <<Application.Application.default_container__docs__sanitizefilename>> as Application.Application.default_container__docs__sanitizefilename
}

@enduml