@startuml
set separator none
title Application - System Context

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<Application>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam rectangle<<FileSystem>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<FileSystem>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<GithubPlantUMLRepo>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<GithubStructurizrRepo>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam rectangle<<LocalSystemsunziputility>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
  shadowing false
}
skinparam person<<User>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
  shadowing false
}

person "==User\n<size:10>[Person]</size>\n\nEnd user who runs archlette commands" <<User>> as User
rectangle "==FileSystem\n<size:10>[Software System]</size>\n\nFile system for reading and writing files" <<FileSystem>> as FileSystem
rectangle "==Github Structurizr Repo\n<size:10>[Software System]</size>\n\nThe github repo hosting the Structurizr CLI releases. https://github.com/structurizr/cli/releases/download/v${TOOL_VERSIONS.structurizr}/structurizr-cli.zip" <<GithubStructurizrRepo>> as GithubStructurizrRepo
rectangle "==Github PlantUML Repo\n<size:10>[Software System]</size>\n\nThe github repo hosting the PlantUML CLI releases. https://github.com/plantuml/plantuml/releases/download/v${TOOL_VERSIONS.plantuml}/plantuml-${TOOL_VERSIONS.plantuml}.jar" <<GithubPlantUMLRepo>> as GithubPlantUMLRepo
rectangle "==Local System's unzip utility\n<size:10>[Software System]</size>\n\nThe zip extraction utility on the local system (unzip on Unix, Expand-Archive on Windows)." <<LocalSystemsunziputility>> as LocalSystemsunziputility
rectangle "==File System\n<size:10>[Software System]</size>\n\nThe local file system for caching downloaded tools." <<FileSystem>> as FileSystem
rectangle "==Application\n<size:10>[Software System]</size>\n\nMain application container" <<Application>> as Application

User -[#707070,thickness=2]-> Application : "<color:#707070>Interacts with CLI"
Application -[#707070,thickness=2]-> FileSystem : "<color:#707070>Uses FileSystem for external system integration"
Application -[#707070,thickness=2]-> GithubStructurizrRepo : "<color:#707070>Uses Github Structurizr Repo for external system integration"
Application -[#707070,thickness=2]-> GithubPlantUMLRepo : "<color:#707070>Uses Github PlantUML Repo for external system integration"
Application -[#707070,thickness=2]-> LocalSystemsunziputility : "<color:#707070>Uses Local System's unzip utility for external system integration"
Application -[#707070,thickness=2]-> FileSystem : "<color:#707070>Uses File System for external system integration"
@enduml