@startuml
set separator none
title @chrislyons-dev/archlette - @chrislyons-dev/archlette - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsloadyamlifexists>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsparseargs>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsrun>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsstagelistfromarg>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsusageandexit>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<chrislyonsdevarchlette.chrislyonsdevarchlette>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

rectangle "@chrislyons-dev/archlette\n<size:10>[Container: Application]</size>" <<chrislyonsdevarchlette.chrislyonsdevarchlette>> {
  rectangle "==cli.ts::usageandexit\n<size:10>[Component: function]</size>" <<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsusageandexit>> as chrislyonsdevarchlette.chrislyonsdevarchlette.clitsusageandexit
  rectangle "==cli.ts::parseargs\n<size:10>[Component: function]</size>" <<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsparseargs>> as chrislyonsdevarchlette.chrislyonsdevarchlette.clitsparseargs
  rectangle "==cli.ts::stagelistfromarg\n<size:10>[Component: function]</size>" <<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsstagelistfromarg>> as chrislyonsdevarchlette.chrislyonsdevarchlette.clitsstagelistfromarg
  rectangle "==cli.ts::loadyamlifexists\n<size:10>[Component: function]</size>" <<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsloadyamlifexists>> as chrislyonsdevarchlette.chrislyonsdevarchlette.clitsloadyamlifexists
  rectangle "==cli.ts::run\n<size:10>[Component: function]</size>" <<chrislyonsdevarchlette.chrislyonsdevarchlette.clitsrun>> as chrislyonsdevarchlette.chrislyonsdevarchlette.clitsrun
}

@enduml