@startuml
set separator none
title Application - Application - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<Application.Application.renderers__plantumlrender>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Application.Application.renderers__run>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Application.Application.renderers__structurizrexport>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Application.Application>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

rectangle "Application\n<size:10>[Container: Application]</size>" <<Application.Application>> {
  rectangle "==renderers__run\n<size:10>[Component: function]</size>\n\nExecute the rendering stage" <<Application.Application.renderers__run>> as Application.Application.renderers__run
  rectangle "==renderers__plantumlrender\n<size:10>[Component: function]</size>\n\nRender PlantUML files to PNG images" <<Application.Application.renderers__plantumlrender>> as Application.Application.renderers__plantumlrender
  rectangle "==renderers__structurizrexport\n<size:10>[Component: function]</size>\n\nExport Structurizr DSL to PlantUML and Mermaid formats" <<Application.Application.renderers__structurizrexport>> as Application.Application.renderers__structurizrexport
}

@enduml