system:
  name: bond-math
  description: Bond mathematics calculation service
  repository: https://github.com/chrislyons-dev/bond-math.git

project:
  name: bond-math
  description: Bond mathematics calculation service

paths:
  output: ./output
  logs: ./logs
  ir_out: ./output/bond-math-ir.json
  dsl_out: ./output/bond-math.dsl
  render_out: ./output/diagrams
  docs_out: ./output/docs

extractors:
  # Wrangler deployment extractor for Cloudflare Workers
  - use: extractors/builtin/basic-wrangler
    inputs:
      include:
        - '~/git/bond-math/iac/workers/daycount.toml'
        - '~/git/bond-math/iac/workers/gateway.toml'
        - '~/git/bond-math/iac/workers/metrics.toml'
        - '~/git/bond-math/iac/workers/pricing.toml'
        - '~/git/bond-math/iac/workers/valuation.toml'

  - use: extractors/builtin/basic-node
    inputs:
      include:
        - '~/git/bond-math/services/gateway/**/*.js'
        - '~/git/bond-math/services/gateway/**/*.jsx'
        - '~/git/bond-math/services/gateway/**/*.ts'
        - '~/git/bond-math/services/gateway/**/*.tsx'
      exclude:
        - '**/node_modules/**'
        - '**/*.test.*'
        - '**/*.spec.*'
        - '**/test/**'
        - '**/tests/**'
        - '**/vitest.config.ts'

  - use: extractors/builtin/basic-node
    inputs:
      include:
        - '~/git/bond-math/services/daycount/**/*.js'
        - '~/git/bond-math/services/daycount/**/*.jsx'
        - '~/git/bond-math/services/daycount/**/*.ts'
        - '~/git/bond-math/services/daycount/**/*.tsx'
      exclude:
        - '**/node_modules/**'
        - '**/*.test.*'
        - '**/*.spec.*'
        - '**/test/**'
        - '**/tests/**'
        - '**/vitest.config.ts'

# ir json in, ir json out (or errors)
validators:
  - use: validators/builtin/base-validator

# ir json in, dsl out
generators:
  - use: generators/builtin/structurizr

# dsl in, images out
# Renderers run sequentially - order matters!
# 1. Export DSL to PlantUML/Mermaid
# 2. Render PlantUML to PNG images
renderers:
  - use: renderers/builtin/structurizr-export
  - use: renderers/builtin/plantuml-render

# dsl & images in, (likely markdown) docs out
docs:
  - use: docs/builtin/markdown-docs
